### ISSUE TITLE
Does the reference to a repository require changing ?

### ISSUE THREAD

**Issue by DeltaCopy** [arcolinuxd/arco-xfce#3]
https://github.com/arcolinuxd/arco-xfce/blob/master/600-additional-arcolinux-software.sh#L64

References arcolinux-xfce4-panel-profiles which doesn't exist in https://github.com/orgs/arcolinux/repositories

From: arcolinux-xfce4-panel-profiles-git
To: **arcolinux-xfce-panel-profiles-git**

**Comment by arcolinuxz** [comment]
indeed

thanks for reporting
